import 'package:cpr_instructor_doc/data/local/app_database.dart';
import 'package:cpr_instructor_doc/domain/checklists/checklist_asset_registry.dart';
import 'package:cpr_instructor_doc/domain/checklists/checklist_definition.dart';
import 'package:cpr_instructor_doc/domain/checklists/checklist_item_definition.dart';

class AdultBlsDefinition {
  static const String sectionPrimary = 'Adult BLS';

  static ChecklistDefinition build() {
    final items = <ChecklistItemDefinition>[
      ChecklistItemDefinition(
        id: 'adult_scene_safety_ppe',
        title: 'Scene safety and PPE',
        instructorPrompt: 'Confirm the scene is safe, apply appropriate PPE, and verbalize safety considerations.',
        imageAssetPath: ChecklistAssetRegistry.pathForItem('adult_scene_safety_ppe'),
        required: true,
        order: 1,
        section: sectionPrimary,
      ),
      ChecklistItemDefinition(
        id: 'adult_responsiveness',
        title: 'Assess responsiveness',
        instructorPrompt: 'Tap and shout: “Are you okay?” Demonstrate a clear responsiveness check.',
        imageAssetPath: ChecklistAssetRegistry.pathForItem('adult_responsiveness'),
        required: true,
        order: 2,
        section: sectionPrimary,
      ),
      ChecklistItemDefinition(
        id: 'adult_activate_emergency_response',
        title: 'Activate emergency response',
        instructorPrompt: 'Direct bystanders to call 911/emergency response and bring the AED.',
        imageAssetPath: ChecklistAssetRegistry.pathForItem('adult_activate_emergency_response'),
        required: true,
        order: 3,
        section: sectionPrimary,
      ),
      ChecklistItemDefinition(
        id: 'adult_retrieve_aed',
        title: 'Retrieve AED',
        instructorPrompt: 'Ensure AED is requested/retrieved as part of the response.',
        imageAssetPath: ChecklistAssetRegistry.pathForItem('adult_retrieve_aed'),
        required: true,
        order: 4,
        section: sectionPrimary,
      ),
      ChecklistItemDefinition(
        id: 'adult_check_breathing_pulse',
        title: 'Check breathing and pulse',
        instructorPrompt: 'Check for normal breathing and carotid pulse simultaneously (≤10 seconds).',
        imageAssetPath: ChecklistAssetRegistry.pathForItem('adult_check_breathing_pulse'),
        required: true,
        order: 5,
        section: sectionPrimary,
      ),
      ChecklistItemDefinition(
        id: 'adult_hand_placement',
        title: 'Correct hand placement',
        instructorPrompt: 'Place hands on the center of the chest (lower half of sternum).',
        imageAssetPath: ChecklistAssetRegistry.pathForItem('adult_hand_placement'),
        required: true,
        order: 6,
        section: sectionPrimary,
      ),
      ChecklistItemDefinition(
        id: 'adult_compression_rate',
        title: 'Compression rate',
        instructorPrompt: 'Demonstrate compressions at an appropriate rate (100–120/min).',
        imageAssetPath: ChecklistAssetRegistry.pathForItem('adult_compression_rate'),
        required: true,
        order: 7,
        section: sectionPrimary,
      ),
      ChecklistItemDefinition(
        id: 'adult_compression_depth',
        title: 'Compression depth',
        instructorPrompt: 'Demonstrate correct depth (at least 2 inches / 5 cm).',
        imageAssetPath: ChecklistAssetRegistry.pathForItem('adult_compression_depth'),
        required: true,
        order: 8,
        section: sectionPrimary,
      ),
      ChecklistItemDefinition(
        id: 'adult_full_recoil',
        title: 'Full chest recoil',
        instructorPrompt: 'Allow full recoil between compressions without leaning.',
        imageAssetPath: ChecklistAssetRegistry.pathForItem('adult_full_recoil'),
        required: true,
        order: 9,
        section: sectionPrimary,
      ),
      ChecklistItemDefinition(
        id: 'adult_minimize_interruptions',
        title: 'Minimize interruptions',
        instructorPrompt: 'Minimize pauses and maintain a smooth rhythm.',
        imageAssetPath: ChecklistAssetRegistry.pathForItem('adult_minimize_interruptions'),
        required: true,
        order: 10,
        section: sectionPrimary,
      ),
      ChecklistItemDefinition(
        id: 'adult_open_airway',
        title: 'Open airway',
        instructorPrompt: 'Open the airway appropriately (head-tilt/chin-lift unless contraindicated).',
        imageAssetPath: ChecklistAssetRegistry.pathForItem('adult_open_airway'),
        required: true,
        order: 11,
        section: sectionPrimary,
      ),
      ChecklistItemDefinition(
        id: 'adult_pocket_mask_ventilation',
        title: 'Pocket-mask ventilation',
        instructorPrompt: 'Demonstrate proper seal and technique using a pocket mask.',
        imageAssetPath: ChecklistAssetRegistry.pathForItem('adult_pocket_mask_ventilation'),
        required: true,
        order: 12,
        section: sectionPrimary,
      ),
      ChecklistItemDefinition(
        id: 'adult_correct_breaths',
        title: 'Correct breaths',
        instructorPrompt: 'Provide breaths over 1 second with visible chest rise; avoid excessive ventilation.',
        imageAssetPath: ChecklistAssetRegistry.pathForItem('adult_correct_breaths'),
        required: true,
        order: 13,
        section: sectionPrimary,
      ),
      ChecklistItemDefinition(
        id: 'adult_30_2_sequence',
        title: '30:2 sequence',
        instructorPrompt: 'Demonstrate 30 compressions followed by 2 breaths with minimal pause.',
        imageAssetPath: ChecklistAssetRegistry.pathForItem('adult_30_2_sequence'),
        required: true,
        order: 14,
        section: sectionPrimary,
      ),
      ChecklistItemDefinition(
        id: 'adult_aed_operation',
        title: 'AED operation',
        instructorPrompt: 'Power on AED, apply pads correctly, follow prompts, clear before shock.',
        imageAssetPath: ChecklistAssetRegistry.pathForItem('adult_aed_operation'),
        required: true,
        order: 15,
        section: sectionPrimary,
      ),
      ChecklistItemDefinition(
        id: 'adult_resume_compressions',
        title: 'Resume compressions',
        instructorPrompt: 'Resume CPR immediately after shock/no-shock decision per prompts.',
        imageAssetPath: ChecklistAssetRegistry.pathForItem('adult_resume_compressions'),
        required: true,
        order: 16,
        section: sectionPrimary,
      ),
      ChecklistItemDefinition(
        id: 'adult_two_rescuer_teamwork',
        title: 'Team / two-rescuer performance (when required)',
        instructorPrompt: 'Demonstrate effective teamwork, role clarity, and smooth transitions when applicable.',
        imageAssetPath: ChecklistAssetRegistry.pathForItem('adult_two_rescuer_teamwork'),
        required: false,
        order: 17,
        section: sectionPrimary,
        optionalTeachingNote: 'Only score this if your class requires a team/two-rescuer demonstration.',
      ),
    ];

    return ChecklistDefinition(type: ChecklistType.adult, title: 'Adult BLS Skills', items: items);
  }
}
