// GENERATED CODE - DO NOT MODIFY BY HAND
//
// Generated by Drift's build_runner integration.

// ignore_for_file: type=lint

part of 'package:cpr_instructor_doc/data/local/app_database.dart';

class $ClassRecordsTable extends ClassRecords with TableInfo<$ClassRecordsTable, ClassRecord> {
  @override
  final GeneratedDatabase attachedDatabase;
  final String? _alias;
  $ClassRecordsTable(this.attachedDatabase, [this._alias]);

  static const VerificationMeta _idMeta = VerificationMeta('id');
  @override
  late final GeneratedColumn<String> id = GeneratedColumn<String>('id', aliasedName, false, type: DriftSqlType.string, requiredDuringInsert: true);

  static const VerificationMeta _classNameMeta = VerificationMeta('className');
  @override
  late final GeneratedColumn<String> className = GeneratedColumn<String>('class_name', aliasedName, false, type: DriftSqlType.string, requiredDuringInsert: true);

  static const VerificationMeta _courseTypeMeta = VerificationMeta('courseType');
  @override
  late final GeneratedColumnWithTypeConverter<CourseType, String> courseType = GeneratedColumn<String>(
    'course_type',
    aliasedName,
    false,
    type: DriftSqlType.string,
    requiredDuringInsert: true,
  ).withConverter<CourseType>(const CourseTypeConverter());

  @override
  late final GeneratedColumn<DateTime> classDate = GeneratedColumn<DateTime>('class_date', aliasedName, true, type: DriftSqlType.dateTime, requiredDuringInsert: false);

  @override
  late final GeneratedColumn<DateTime> startTime = GeneratedColumn<DateTime>('start_time', aliasedName, true, type: DriftSqlType.dateTime, requiredDuringInsert: false);

  @override
  late final GeneratedColumn<DateTime> endTime = GeneratedColumn<DateTime>('end_time', aliasedName, true, type: DriftSqlType.dateTime, requiredDuringInsert: false);

  @override
  late final GeneratedColumn<String> location = GeneratedColumn<String>('location', aliasedName, true, type: DriftSqlType.string, requiredDuringInsert: false);

  @override
  late final GeneratedColumn<String> leadInstructor = GeneratedColumn<String>('lead_instructor', aliasedName, true, type: DriftSqlType.string, requiredDuringInsert: false);

  @override
  late final GeneratedColumn<String> additionalInstructor = GeneratedColumn<String>('additional_instructor', aliasedName, true, type: DriftSqlType.string, requiredDuringInsert: false);

  @override
  late final GeneratedColumn<String> trainingCenter = GeneratedColumn<String>('training_center', aliasedName, true, type: DriftSqlType.string, requiredDuringInsert: false);

  @override
  late final GeneratedColumn<String> trainingSite = GeneratedColumn<String>('training_site', aliasedName, true, type: DriftSqlType.string, requiredDuringInsert: false);

  @override
  late final GeneratedColumn<bool> writtenTestRequired = GeneratedColumn<bool>(
    'written_test_required',
    aliasedName,
    false,
    type: DriftSqlType.bool,
    requiredDuringInsert: false,
    defaultConstraints: GeneratedColumn.constraintIsAlways('CHECK ("written_test_required" IN (0, 1))'),
    defaultValue: const Constant(false),
  );

  @override
  late final GeneratedColumn<int> passingScore = GeneratedColumn<int>('passing_score', aliasedName, true, type: DriftSqlType.int, requiredDuringInsert: false);

  @override
  late final GeneratedColumn<bool> ccfRequired = GeneratedColumn<bool>(
    'ccf_required',
    aliasedName,
    false,
    type: DriftSqlType.bool,
    requiredDuringInsert: false,
    defaultConstraints: GeneratedColumn.constraintIsAlways('CHECK ("ccf_required" IN (0, 1))'),
    defaultValue: const Constant(false),
  );

  @override
  late final GeneratedColumn<DateTime> defaultSkillsCheckOffDate = GeneratedColumn<DateTime>(
    'default_skills_check_off_date',
    aliasedName,
    true,
    type: DriftSqlType.dateTime,
    requiredDuringInsert: false,
  );

  @override
  late final GeneratedColumn<DateTime> defaultIssueDate = GeneratedColumn<DateTime>('default_issue_date', aliasedName, true, type: DriftSqlType.dateTime, requiredDuringInsert: false);

  @override
  late final GeneratedColumn<bool> isActive = GeneratedColumn<bool>(
    'is_active',
    aliasedName,
    false,
    type: DriftSqlType.bool,
    requiredDuringInsert: false,
    defaultConstraints: GeneratedColumn.constraintIsAlways('CHECK ("is_active" IN (0, 1))'),
    defaultValue: const Constant(false),
  );

  @override
  late final GeneratedColumn<DateTime> createdAt = GeneratedColumn<DateTime>('created_at', aliasedName, false, type: DriftSqlType.dateTime, requiredDuringInsert: true);

  @override
  late final GeneratedColumn<DateTime> updatedAt = GeneratedColumn<DateTime>('updated_at', aliasedName, false, type: DriftSqlType.dateTime, requiredDuringInsert: true);

  @override
  List<GeneratedColumn> get $columns => [
    id,
    className,
    courseType,
    classDate,
    startTime,
    endTime,
    location,
    leadInstructor,
    additionalInstructor,
    trainingCenter,
    trainingSite,
    writtenTestRequired,
    passingScore,
    ccfRequired,
    defaultSkillsCheckOffDate,
    defaultIssueDate,
    isActive,
    createdAt,
    updatedAt,
  ];

  @override
  String get aliasedName => _alias ?? 'class_records';
  @override
  String get actualTableName => 'class_records';

  @override
  VerificationContext validateIntegrity(Insertable<ClassRecord> instance, {bool isInserting = false}) {
    final ctx = VerificationContext();
    final data = instance.toColumns(true);
    if (data.containsKey('id')) ctx.handle(_idMeta, id.isAcceptableOrUnknown(data['id']!, _idMeta));
    if (data.containsKey('class_name')) ctx.handle(_classNameMeta, className.isAcceptableOrUnknown(data['class_name']!, _classNameMeta));
    if (data.containsKey('course_type')) ctx.handle(_courseTypeMeta, const VerificationResult.success());
    if (data.containsKey('class_date')) ctx.handle(const VerificationMeta('classDate'), classDate.isAcceptableOrUnknown(data['class_date']!, const VerificationMeta('classDate')));
    if (data.containsKey('start_time')) ctx.handle(const VerificationMeta('startTime'), startTime.isAcceptableOrUnknown(data['start_time']!, const VerificationMeta('startTime')));
    if (data.containsKey('end_time')) ctx.handle(const VerificationMeta('endTime'), endTime.isAcceptableOrUnknown(data['end_time']!, const VerificationMeta('endTime')));
    if (data.containsKey('created_at')) ctx.handle(const VerificationMeta('createdAt'), createdAt.isAcceptableOrUnknown(data['created_at']!, const VerificationMeta('createdAt')));
    if (data.containsKey('updated_at')) ctx.handle(const VerificationMeta('updatedAt'), updatedAt.isAcceptableOrUnknown(data['updated_at']!, const VerificationMeta('updatedAt')));
    return ctx;
  }

  @override
  Set<GeneratedColumn> get $primaryKey => {id};

  @override
  ClassRecord map(Map<String, dynamic> data, {String? tablePrefix}) {
    final effectivePrefix = tablePrefix != null ? '$tablePrefix.' : '';
    return ClassRecord(
      id: attachedDatabase.typeMapping.read(DriftSqlType.string, data['${effectivePrefix}id'])!,
      className: attachedDatabase.typeMapping.read(DriftSqlType.string, data['${effectivePrefix}class_name'])!,
      courseType: courseType.converter.fromSql(attachedDatabase.typeMapping.read(DriftSqlType.string, data['${effectivePrefix}course_type'])!),
      classDate: attachedDatabase.typeMapping.read(DriftSqlType.dateTime, data['${effectivePrefix}class_date']),
      startTime: attachedDatabase.typeMapping.read(DriftSqlType.dateTime, data['${effectivePrefix}start_time']),
      endTime: attachedDatabase.typeMapping.read(DriftSqlType.dateTime, data['${effectivePrefix}end_time']),
      location: attachedDatabase.typeMapping.read(DriftSqlType.string, data['${effectivePrefix}location']),
      leadInstructor: attachedDatabase.typeMapping.read(DriftSqlType.string, data['${effectivePrefix}lead_instructor']),
      additionalInstructor: attachedDatabase.typeMapping.read(DriftSqlType.string, data['${effectivePrefix}additional_instructor']),
      trainingCenter: attachedDatabase.typeMapping.read(DriftSqlType.string, data['${effectivePrefix}training_center']),
      trainingSite: attachedDatabase.typeMapping.read(DriftSqlType.string, data['${effectivePrefix}training_site']),
      writtenTestRequired: attachedDatabase.typeMapping.read(DriftSqlType.bool, data['${effectivePrefix}written_test_required'])!,
      passingScore: attachedDatabase.typeMapping.read(DriftSqlType.int, data['${effectivePrefix}passing_score']),
      ccfRequired: attachedDatabase.typeMapping.read(DriftSqlType.bool, data['${effectivePrefix}ccf_required'])!,
      defaultSkillsCheckOffDate: attachedDatabase.typeMapping.read(DriftSqlType.dateTime, data['${effectivePrefix}default_skills_check_off_date']),
      defaultIssueDate: attachedDatabase.typeMapping.read(DriftSqlType.dateTime, data['${effectivePrefix}default_issue_date']),
      isActive: attachedDatabase.typeMapping.read(DriftSqlType.bool, data['${effectivePrefix}is_active'])!,
      createdAt: attachedDatabase.typeMapping.read(DriftSqlType.dateTime, data['${effectivePrefix}created_at'])!,
      updatedAt: attachedDatabase.typeMapping.read(DriftSqlType.dateTime, data['${effectivePrefix}updated_at'])!,
    );
  }

  @override
  $ClassRecordsTable createAlias(String alias) => $ClassRecordsTable(attachedDatabase, alias);
}

class ClassRecord extends DataClass implements Insertable<ClassRecord> {
  const ClassRecord({
    required this.id,
    required this.className,
    required this.courseType,
    this.classDate,
    this.startTime,
    this.endTime,
    this.location,
    this.leadInstructor,
    this.additionalInstructor,
    this.trainingCenter,
    this.trainingSite,
    required this.writtenTestRequired,
    this.passingScore,
    required this.ccfRequired,
    this.defaultSkillsCheckOffDate,
    this.defaultIssueDate,
    required this.isActive,
    required this.createdAt,
    required this.updatedAt,
  });

  final String id;
  final String className;
  final CourseType courseType;
  final DateTime? classDate;
  final DateTime? startTime;
  final DateTime? endTime;
  final String? location;
  final String? leadInstructor;
  final String? additionalInstructor;
  final String? trainingCenter;
  final String? trainingSite;
  final bool writtenTestRequired;
  final int? passingScore;
  final bool ccfRequired;
  final DateTime? defaultSkillsCheckOffDate;
  final DateTime? defaultIssueDate;
  final bool isActive;
  final DateTime createdAt;
  final DateTime updatedAt;

  @override
  Map<String, Expression> toColumns(bool nullToAbsent) {
    final map = <String, Expression>{};
    map['id'] = Variable<String>(id);
    map['class_name'] = Variable<String>(className);
    map['course_type'] = Variable<String>(const CourseTypeConverter().toSql(courseType));
    if (!nullToAbsent || classDate != null) map['class_date'] = Variable<DateTime>(classDate!);
    if (!nullToAbsent || startTime != null) map['start_time'] = Variable<DateTime>(startTime!);
    if (!nullToAbsent || endTime != null) map['end_time'] = Variable<DateTime>(endTime!);
    if (!nullToAbsent || location != null) map['location'] = Variable<String>(location!);
    if (!nullToAbsent || leadInstructor != null) map['lead_instructor'] = Variable<String>(leadInstructor!);
    if (!nullToAbsent || additionalInstructor != null) map['additional_instructor'] = Variable<String>(additionalInstructor!);
    if (!nullToAbsent || trainingCenter != null) map['training_center'] = Variable<String>(trainingCenter!);
    if (!nullToAbsent || trainingSite != null) map['training_site'] = Variable<String>(trainingSite!);
    map['written_test_required'] = Variable<bool>(writtenTestRequired);
    if (!nullToAbsent || passingScore != null) map['passing_score'] = Variable<int>(passingScore!);
    map['ccf_required'] = Variable<bool>(ccfRequired);
    if (!nullToAbsent || defaultSkillsCheckOffDate != null) {
      map['default_skills_check_off_date'] = Variable<DateTime>(defaultSkillsCheckOffDate!);
    }
    if (!nullToAbsent || defaultIssueDate != null) map['default_issue_date'] = Variable<DateTime>(defaultIssueDate!);
    map['is_active'] = Variable<bool>(isActive);
    map['created_at'] = Variable<DateTime>(createdAt);
    map['updated_at'] = Variable<DateTime>(updatedAt);
    return map;
  }

  ClassRecordsCompanion toCompanion(bool nullToAbsent) => ClassRecordsCompanion(
    id: Value(id),
    className: Value(className),
    courseType: Value(courseType),
    classDate: classDate == null && nullToAbsent ? const Value.absent() : Value(classDate),
    startTime: startTime == null && nullToAbsent ? const Value.absent() : Value(startTime),
    endTime: endTime == null && nullToAbsent ? const Value.absent() : Value(endTime),
    location: location == null && nullToAbsent ? const Value.absent() : Value(location),
    leadInstructor: leadInstructor == null && nullToAbsent ? const Value.absent() : Value(leadInstructor),
    additionalInstructor: additionalInstructor == null && nullToAbsent ? const Value.absent() : Value(additionalInstructor),
    trainingCenter: trainingCenter == null && nullToAbsent ? const Value.absent() : Value(trainingCenter),
    trainingSite: trainingSite == null && nullToAbsent ? const Value.absent() : Value(trainingSite),
    writtenTestRequired: Value(writtenTestRequired),
    passingScore: passingScore == null && nullToAbsent ? const Value.absent() : Value(passingScore),
    ccfRequired: Value(ccfRequired),
    defaultSkillsCheckOffDate: defaultSkillsCheckOffDate == null && nullToAbsent ? const Value.absent() : Value(defaultSkillsCheckOffDate),
    defaultIssueDate: defaultIssueDate == null && nullToAbsent ? const Value.absent() : Value(defaultIssueDate),
    isActive: Value(isActive),
    createdAt: Value(createdAt),
    updatedAt: Value(updatedAt),
  );

  @override
  Map<String, dynamic> toJson({ValueSerializer? serializer}) {
    serializer ??= driftRuntimeOptions.defaultSerializer;
    return <String, dynamic>{
      'id': serializer.toJson<String>(id),
      'className': serializer.toJson<String>(className),
      'courseType': serializer.toJson<String>(const CourseTypeConverter().toSql(courseType)),
      'classDate': serializer.toJson<DateTime?>(classDate),
      'startTime': serializer.toJson<DateTime?>(startTime),
      'endTime': serializer.toJson<DateTime?>(endTime),
      'location': serializer.toJson<String?>(location),
      'leadInstructor': serializer.toJson<String?>(leadInstructor),
      'additionalInstructor': serializer.toJson<String?>(additionalInstructor),
      'trainingCenter': serializer.toJson<String?>(trainingCenter),
      'trainingSite': serializer.toJson<String?>(trainingSite),
      'writtenTestRequired': serializer.toJson<bool>(writtenTestRequired),
      'passingScore': serializer.toJson<int?>(passingScore),
      'ccfRequired': serializer.toJson<bool>(ccfRequired),
      'defaultSkillsCheckOffDate': serializer.toJson<DateTime?>(defaultSkillsCheckOffDate),
      'defaultIssueDate': serializer.toJson<DateTime?>(defaultIssueDate),
      'isActive': serializer.toJson<bool>(isActive),
      'createdAt': serializer.toJson<DateTime>(createdAt),
      'updatedAt': serializer.toJson<DateTime>(updatedAt),
    };
  }
}

class ClassRecordsCompanion extends UpdateCompanion<ClassRecord> {
  const ClassRecordsCompanion({
    this.id = const Value.absent(),
    this.className = const Value.absent(),
    this.courseType = const Value.absent(),
    this.classDate = const Value.absent(),
    this.startTime = const Value.absent(),
    this.endTime = const Value.absent(),
    this.location = const Value.absent(),
    this.leadInstructor = const Value.absent(),
    this.additionalInstructor = const Value.absent(),
    this.trainingCenter = const Value.absent(),
    this.trainingSite = const Value.absent(),
    this.writtenTestRequired = const Value.absent(),
    this.passingScore = const Value.absent(),
    this.ccfRequired = const Value.absent(),
    this.defaultSkillsCheckOffDate = const Value.absent(),
    this.defaultIssueDate = const Value.absent(),
    this.isActive = const Value.absent(),
    this.createdAt = const Value.absent(),
    this.updatedAt = const Value.absent(),
  });

  final Value<String> id;
  final Value<String> className;
  final Value<CourseType> courseType;
  final Value<DateTime?> classDate;
  final Value<DateTime?> startTime;
  final Value<DateTime?> endTime;
  final Value<String?> location;
  final Value<String?> leadInstructor;
  final Value<String?> additionalInstructor;
  final Value<String?> trainingCenter;
  final Value<String?> trainingSite;
  final Value<bool> writtenTestRequired;
  final Value<int?> passingScore;
  final Value<bool> ccfRequired;
  final Value<DateTime?> defaultSkillsCheckOffDate;
  final Value<DateTime?> defaultIssueDate;
  final Value<bool> isActive;
  final Value<DateTime> createdAt;
  final Value<DateTime> updatedAt;

  ClassRecordsCompanion copyWith({
    Value<String>? id,
    Value<String>? className,
    Value<CourseType>? courseType,
    Value<DateTime?>? classDate,
    Value<DateTime?>? startTime,
    Value<DateTime?>? endTime,
    Value<String?>? location,
    Value<String?>? leadInstructor,
    Value<String?>? additionalInstructor,
    Value<String?>? trainingCenter,
    Value<String?>? trainingSite,
    Value<bool>? writtenTestRequired,
    Value<int?>? passingScore,
    Value<bool>? ccfRequired,
    Value<DateTime?>? defaultSkillsCheckOffDate,
    Value<DateTime?>? defaultIssueDate,
    Value<bool>? isActive,
    Value<DateTime>? createdAt,
    Value<DateTime>? updatedAt,
  }) => ClassRecordsCompanion(
    id: id ?? this.id,
    className: className ?? this.className,
    courseType: courseType ?? this.courseType,
    classDate: classDate ?? this.classDate,
    startTime: startTime ?? this.startTime,
    endTime: endTime ?? this.endTime,
    location: location ?? this.location,
    leadInstructor: leadInstructor ?? this.leadInstructor,
    additionalInstructor: additionalInstructor ?? this.additionalInstructor,
    trainingCenter: trainingCenter ?? this.trainingCenter,
    trainingSite: trainingSite ?? this.trainingSite,
    writtenTestRequired: writtenTestRequired ?? this.writtenTestRequired,
    passingScore: passingScore ?? this.passingScore,
    ccfRequired: ccfRequired ?? this.ccfRequired,
    defaultSkillsCheckOffDate: defaultSkillsCheckOffDate ?? this.defaultSkillsCheckOffDate,
    defaultIssueDate: defaultIssueDate ?? this.defaultIssueDate,
    isActive: isActive ?? this.isActive,
    createdAt: createdAt ?? this.createdAt,
    updatedAt: updatedAt ?? this.updatedAt,
  );

  @override
  Map<String, Expression> toColumns(bool nullToAbsent) {
    final map = <String, Expression>{};
    if (id.present) map['id'] = Variable<String>(id.value);
    if (className.present) map['class_name'] = Variable<String>(className.value);
    if (courseType.present) map['course_type'] = Variable<String>(const CourseTypeConverter().toSql(courseType.value));
    if (classDate.present) {
      final v = classDate.value;
      if (!nullToAbsent || v != null) map['class_date'] = Variable<DateTime>(v!);
    }
    if (startTime.present) {
      final v = startTime.value;
      if (!nullToAbsent || v != null) map['start_time'] = Variable<DateTime>(v!);
    }
    if (endTime.present) {
      final v = endTime.value;
      if (!nullToAbsent || v != null) map['end_time'] = Variable<DateTime>(v!);
    }
    if (location.present) {
      final v = location.value;
      if (!nullToAbsent || v != null) map['location'] = Variable<String>(v!);
    }
    if (leadInstructor.present) {
      final v = leadInstructor.value;
      if (!nullToAbsent || v != null) map['lead_instructor'] = Variable<String>(v!);
    }
    if (additionalInstructor.present) {
      final v = additionalInstructor.value;
      if (!nullToAbsent || v != null) map['additional_instructor'] = Variable<String>(v!);
    }
    if (trainingCenter.present) {
      final v = trainingCenter.value;
      if (!nullToAbsent || v != null) map['training_center'] = Variable<String>(v!);
    }
    if (trainingSite.present) {
      final v = trainingSite.value;
      if (!nullToAbsent || v != null) map['training_site'] = Variable<String>(v!);
    }
    if (writtenTestRequired.present) map['written_test_required'] = Variable<bool>(writtenTestRequired.value);
    if (passingScore.present) {
      final v = passingScore.value;
      if (!nullToAbsent || v != null) map['passing_score'] = Variable<int>(v!);
    }
    if (ccfRequired.present) map['ccf_required'] = Variable<bool>(ccfRequired.value);
    if (defaultSkillsCheckOffDate.present) {
      final v = defaultSkillsCheckOffDate.value;
      if (!nullToAbsent || v != null) map['default_skills_check_off_date'] = Variable<DateTime>(v!);
    }
    if (defaultIssueDate.present) {
      final v = defaultIssueDate.value;
      if (!nullToAbsent || v != null) map['default_issue_date'] = Variable<DateTime>(v!);
    }
    if (isActive.present) map['is_active'] = Variable<bool>(isActive.value);
    if (createdAt.present) map['created_at'] = Variable<DateTime>(createdAt.value);
    if (updatedAt.present) map['updated_at'] = Variable<DateTime>(updatedAt.value);
    return map;
  }
}

class $StudentRecordsTable extends StudentRecords with TableInfo<$StudentRecordsTable, StudentRecord> {
  @override
  final GeneratedDatabase attachedDatabase;
  final String? _alias;
  $StudentRecordsTable(this.attachedDatabase, [this._alias]);

  @override
  late final GeneratedColumn<String> id = GeneratedColumn<String>('id', aliasedName, false, type: DriftSqlType.string, requiredDuringInsert: true);
  @override
  late final GeneratedColumn<String> classId = GeneratedColumn<String>(
    'class_id',
    aliasedName,
    false,
    type: DriftSqlType.string,
    requiredDuringInsert: true,
    defaultConstraints: GeneratedColumn.constraintIsAlways('REFERENCES "class_records" ("id") ON DELETE RESTRICT'),
  );
  @override
  late final GeneratedColumn<String> displayName = GeneratedColumn<String>('display_name', aliasedName, false, type: DriftSqlType.string, requiredDuringInsert: true);
  @override
  late final GeneratedColumn<String> originalFullName = GeneratedColumn<String>('original_full_name', aliasedName, true, type: DriftSqlType.string, requiredDuringInsert: false);
  @override
  late final GeneratedColumn<String> firstName = GeneratedColumn<String>('first_name', aliasedName, true, type: DriftSqlType.string, requiredDuringInsert: false);
  @override
  late final GeneratedColumn<String> lastName = GeneratedColumn<String>('last_name', aliasedName, true, type: DriftSqlType.string, requiredDuringInsert: false);
  @override
  late final GeneratedColumn<String> email = GeneratedColumn<String>('email', aliasedName, true, type: DriftSqlType.string, requiredDuringInsert: false);
  @override
  late final GeneratedColumn<String> phone = GeneratedColumn<String>('phone', aliasedName, true, type: DriftSqlType.string, requiredDuringInsert: false);
  @override
  late final GeneratedColumn<bool> nameNeedsReview = GeneratedColumn<bool>(
    'name_needs_review',
    aliasedName,
    false,
    type: DriftSqlType.bool,
    requiredDuringInsert: false,
    defaultConstraints: GeneratedColumn.constraintIsAlways('CHECK ("name_needs_review" IN (0, 1))'),
    defaultValue: const Constant(false),
  );

  @override
  late final GeneratedColumn<int> writtenTestScore = GeneratedColumn<int>('written_test_score', aliasedName, true, type: DriftSqlType.int, requiredDuringInsert: false);

  @override
  late final GeneratedColumn<bool> writtenTestingFinalized = GeneratedColumn<bool>(
    'written_testing_finalized',
    aliasedName,
    false,
    type: DriftSqlType.bool,
    requiredDuringInsert: false,
    defaultConstraints: GeneratedColumn.constraintIsAlways('CHECK ("written_testing_finalized" IN (0, 1))'),
    defaultValue: const Constant(false),
  );

  @override
  late final GeneratedColumn<DateTime> skillsCheckOffDate = GeneratedColumn<DateTime>(
    'skills_check_off_date',
    aliasedName,
    true,
    type: DriftSqlType.dateTime,
    requiredDuringInsert: false,
  );

  @override
  late final GeneratedColumn<DateTime> issueDate = GeneratedColumn<DateTime>('issue_date', aliasedName, true, type: DriftSqlType.dateTime, requiredDuringInsert: false);
  @override
  late final GeneratedColumn<DateTime> createdAt = GeneratedColumn<DateTime>('created_at', aliasedName, false, type: DriftSqlType.dateTime, requiredDuringInsert: true);
  @override
  late final GeneratedColumn<DateTime> updatedAt = GeneratedColumn<DateTime>('updated_at', aliasedName, false, type: DriftSqlType.dateTime, requiredDuringInsert: true);

  @override
  List<GeneratedColumn> get $columns => [
    id,
    classId,
    displayName,
    originalFullName,
    firstName,
    lastName,
    email,
    phone,
    nameNeedsReview,
    writtenTestScore,
    writtenTestingFinalized,
    skillsCheckOffDate,
    issueDate,
    createdAt,
    updatedAt,
  ];

  @override
  String get aliasedName => _alias ?? 'student_records';
  @override
  String get actualTableName => 'student_records';

  @override
  VerificationContext validateIntegrity(Insertable<StudentRecord> instance, {bool isInserting = false}) {
    final ctx = VerificationContext();
    final data = instance.toColumns(true);
    if (data.containsKey('id')) ctx.handle(const VerificationMeta('id'), id.isAcceptableOrUnknown(data['id']!, const VerificationMeta('id')));
    if (data.containsKey('class_id')) ctx.handle(const VerificationMeta('classId'), classId.isAcceptableOrUnknown(data['class_id']!, const VerificationMeta('classId')));
    if (data.containsKey('display_name')) {
      ctx.handle(const VerificationMeta('displayName'), displayName.isAcceptableOrUnknown(data['display_name']!, const VerificationMeta('displayName')));
    }
    if (data.containsKey('created_at')) ctx.handle(const VerificationMeta('createdAt'), createdAt.isAcceptableOrUnknown(data['created_at']!, const VerificationMeta('createdAt')));
    if (data.containsKey('updated_at')) ctx.handle(const VerificationMeta('updatedAt'), updatedAt.isAcceptableOrUnknown(data['updated_at']!, const VerificationMeta('updatedAt')));
    return ctx;
  }

  @override
  Set<GeneratedColumn> get $primaryKey => {id};

  @override
  StudentRecord map(Map<String, dynamic> data, {String? tablePrefix}) {
    final effectivePrefix = tablePrefix != null ? '$tablePrefix.' : '';
    return StudentRecord(
      id: attachedDatabase.typeMapping.read(DriftSqlType.string, data['${effectivePrefix}id'])!,
      classId: attachedDatabase.typeMapping.read(DriftSqlType.string, data['${effectivePrefix}class_id'])!,
      displayName: attachedDatabase.typeMapping.read(DriftSqlType.string, data['${effectivePrefix}display_name'])!,
      originalFullName: attachedDatabase.typeMapping.read(DriftSqlType.string, data['${effectivePrefix}original_full_name']),
      firstName: attachedDatabase.typeMapping.read(DriftSqlType.string, data['${effectivePrefix}first_name']),
      lastName: attachedDatabase.typeMapping.read(DriftSqlType.string, data['${effectivePrefix}last_name']),
      email: attachedDatabase.typeMapping.read(DriftSqlType.string, data['${effectivePrefix}email']),
      phone: attachedDatabase.typeMapping.read(DriftSqlType.string, data['${effectivePrefix}phone']),
      nameNeedsReview: attachedDatabase.typeMapping.read(DriftSqlType.bool, data['${effectivePrefix}name_needs_review'])!,
      writtenTestScore: attachedDatabase.typeMapping.read(DriftSqlType.int, data['${effectivePrefix}written_test_score']),
      writtenTestingFinalized: attachedDatabase.typeMapping.read(DriftSqlType.bool, data['${effectivePrefix}written_testing_finalized'])!,
      skillsCheckOffDate: attachedDatabase.typeMapping.read(DriftSqlType.dateTime, data['${effectivePrefix}skills_check_off_date']),
      issueDate: attachedDatabase.typeMapping.read(DriftSqlType.dateTime, data['${effectivePrefix}issue_date']),
      createdAt: attachedDatabase.typeMapping.read(DriftSqlType.dateTime, data['${effectivePrefix}created_at'])!,
      updatedAt: attachedDatabase.typeMapping.read(DriftSqlType.dateTime, data['${effectivePrefix}updated_at'])!,
    );
  }

  @override
  $StudentRecordsTable createAlias(String alias) => $StudentRecordsTable(attachedDatabase, alias);
}

class StudentRecord extends DataClass implements Insertable<StudentRecord> {
  const StudentRecord({
    required this.id,
    required this.classId,
    required this.displayName,
    this.originalFullName,
    this.firstName,
    this.lastName,
    this.email,
    this.phone,
    required this.nameNeedsReview,
    this.writtenTestScore,
    required this.writtenTestingFinalized,
    this.skillsCheckOffDate,
    this.issueDate,
    required this.createdAt,
    required this.updatedAt,
  });

  final String id;
  final String classId;
  final String displayName;
  final String? originalFullName;
  final String? firstName;
  final String? lastName;
  final String? email;
  final String? phone;
  final bool nameNeedsReview;
  final int? writtenTestScore;
  final bool writtenTestingFinalized;
  final DateTime? skillsCheckOffDate;
  final DateTime? issueDate;
  final DateTime createdAt;
  final DateTime updatedAt;

  @override
  Map<String, Expression> toColumns(bool nullToAbsent) {
    final map = <String, Expression>{};
    map['id'] = Variable<String>(id);
    map['class_id'] = Variable<String>(classId);
    map['display_name'] = Variable<String>(displayName);
    if (!nullToAbsent || originalFullName != null) map['original_full_name'] = Variable<String>(originalFullName!);
    if (!nullToAbsent || firstName != null) map['first_name'] = Variable<String>(firstName!);
    if (!nullToAbsent || lastName != null) map['last_name'] = Variable<String>(lastName!);
    if (!nullToAbsent || email != null) map['email'] = Variable<String>(email!);
    if (!nullToAbsent || phone != null) map['phone'] = Variable<String>(phone!);
    map['name_needs_review'] = Variable<bool>(nameNeedsReview);
    if (!nullToAbsent || writtenTestScore != null) map['written_test_score'] = Variable<int>(writtenTestScore!);
    map['written_testing_finalized'] = Variable<bool>(writtenTestingFinalized);
    if (!nullToAbsent || skillsCheckOffDate != null) map['skills_check_off_date'] = Variable<DateTime>(skillsCheckOffDate!);
    if (!nullToAbsent || issueDate != null) map['issue_date'] = Variable<DateTime>(issueDate!);
    map['created_at'] = Variable<DateTime>(createdAt);
    map['updated_at'] = Variable<DateTime>(updatedAt);
    return map;
  }

  StudentRecordsCompanion toCompanion(bool nullToAbsent) => StudentRecordsCompanion(
    id: Value(id),
    classId: Value(classId),
    displayName: Value(displayName),
    originalFullName: originalFullName == null && nullToAbsent ? const Value.absent() : Value(originalFullName),
    firstName: firstName == null && nullToAbsent ? const Value.absent() : Value(firstName),
    lastName: lastName == null && nullToAbsent ? const Value.absent() : Value(lastName),
    email: email == null && nullToAbsent ? const Value.absent() : Value(email),
    phone: phone == null && nullToAbsent ? const Value.absent() : Value(phone),
    nameNeedsReview: Value(nameNeedsReview),
    writtenTestScore: writtenTestScore == null && nullToAbsent ? const Value.absent() : Value(writtenTestScore),
    writtenTestingFinalized: Value(writtenTestingFinalized),
    skillsCheckOffDate: skillsCheckOffDate == null && nullToAbsent ? const Value.absent() : Value(skillsCheckOffDate),
    issueDate: issueDate == null && nullToAbsent ? const Value.absent() : Value(issueDate),
    createdAt: Value(createdAt),
    updatedAt: Value(updatedAt),
  );

  @override
  Map<String, dynamic> toJson({ValueSerializer? serializer}) {
    serializer ??= driftRuntimeOptions.defaultSerializer;
    return <String, dynamic>{
      'id': serializer.toJson<String>(id),
      'classId': serializer.toJson<String>(classId),
      'displayName': serializer.toJson<String>(displayName),
      'originalFullName': serializer.toJson<String?>(originalFullName),
      'firstName': serializer.toJson<String?>(firstName),
      'lastName': serializer.toJson<String?>(lastName),
      'email': serializer.toJson<String?>(email),
      'phone': serializer.toJson<String?>(phone),
      'nameNeedsReview': serializer.toJson<bool>(nameNeedsReview),
      'writtenTestScore': serializer.toJson<int?>(writtenTestScore),
      'writtenTestingFinalized': serializer.toJson<bool>(writtenTestingFinalized),
      'skillsCheckOffDate': serializer.toJson<DateTime?>(skillsCheckOffDate),
      'issueDate': serializer.toJson<DateTime?>(issueDate),
      'createdAt': serializer.toJson<DateTime>(createdAt),
      'updatedAt': serializer.toJson<DateTime>(updatedAt),
    };
  }
}

class StudentRecordsCompanion extends UpdateCompanion<StudentRecord> {
  const StudentRecordsCompanion({
    this.id = const Value.absent(),
    this.classId = const Value.absent(),
    this.displayName = const Value.absent(),
    this.originalFullName = const Value.absent(),
    this.firstName = const Value.absent(),
    this.lastName = const Value.absent(),
    this.email = const Value.absent(),
    this.phone = const Value.absent(),
    this.nameNeedsReview = const Value.absent(),
    this.writtenTestScore = const Value.absent(),
    this.writtenTestingFinalized = const Value.absent(),
    this.skillsCheckOffDate = const Value.absent(),
    this.issueDate = const Value.absent(),
    this.createdAt = const Value.absent(),
    this.updatedAt = const Value.absent(),
  });

  final Value<String> id;
  final Value<String> classId;
  final Value<String> displayName;
  final Value<String?> originalFullName;
  final Value<String?> firstName;
  final Value<String?> lastName;
  final Value<String?> email;
  final Value<String?> phone;
  final Value<bool> nameNeedsReview;
  final Value<int?> writtenTestScore;
  final Value<bool> writtenTestingFinalized;
  final Value<DateTime?> skillsCheckOffDate;
  final Value<DateTime?> issueDate;
  final Value<DateTime> createdAt;
  final Value<DateTime> updatedAt;

  StudentRecordsCompanion copyWith({
    Value<String>? id,
    Value<String>? classId,
    Value<String>? displayName,
    Value<String?>? originalFullName,
    Value<String?>? firstName,
    Value<String?>? lastName,
    Value<String?>? email,
    Value<String?>? phone,
    Value<bool>? nameNeedsReview,
    Value<int?>? writtenTestScore,
    Value<bool>? writtenTestingFinalized,
    Value<DateTime?>? skillsCheckOffDate,
    Value<DateTime?>? issueDate,
    Value<DateTime>? createdAt,
    Value<DateTime>? updatedAt,
  }) => StudentRecordsCompanion(
    id: id ?? this.id,
    classId: classId ?? this.classId,
    displayName: displayName ?? this.displayName,
    originalFullName: originalFullName ?? this.originalFullName,
    firstName: firstName ?? this.firstName,
    lastName: lastName ?? this.lastName,
    email: email ?? this.email,
    phone: phone ?? this.phone,
    nameNeedsReview: nameNeedsReview ?? this.nameNeedsReview,
    writtenTestScore: writtenTestScore ?? this.writtenTestScore,
    writtenTestingFinalized: writtenTestingFinalized ?? this.writtenTestingFinalized,
    skillsCheckOffDate: skillsCheckOffDate ?? this.skillsCheckOffDate,
    issueDate: issueDate ?? this.issueDate,
    createdAt: createdAt ?? this.createdAt,
    updatedAt: updatedAt ?? this.updatedAt,
  );

  @override
  Map<String, Expression> toColumns(bool nullToAbsent) {
    final map = <String, Expression>{};
    if (id.present) map['id'] = Variable<String>(id.value);
    if (classId.present) map['class_id'] = Variable<String>(classId.value);
    if (displayName.present) map['display_name'] = Variable<String>(displayName.value);
    if (originalFullName.present) {
      final v = originalFullName.value;
      if (!nullToAbsent || v != null) map['original_full_name'] = Variable<String>(v!);
    }
    if (firstName.present) {
      final v = firstName.value;
      if (!nullToAbsent || v != null) map['first_name'] = Variable<String>(v!);
    }
    if (lastName.present) {
      final v = lastName.value;
      if (!nullToAbsent || v != null) map['last_name'] = Variable<String>(v!);
    }
    if (email.present) {
      final v = email.value;
      if (!nullToAbsent || v != null) map['email'] = Variable<String>(v!);
    }
    if (phone.present) {
      final v = phone.value;
      if (!nullToAbsent || v != null) map['phone'] = Variable<String>(v!);
    }
    if (nameNeedsReview.present) map['name_needs_review'] = Variable<bool>(nameNeedsReview.value);
    if (writtenTestScore.present) {
      final v = writtenTestScore.value;
      if (!nullToAbsent || v != null) map['written_test_score'] = Variable<int>(v!);
    }
    if (writtenTestingFinalized.present) map['written_testing_finalized'] = Variable<bool>(writtenTestingFinalized.value);
    if (skillsCheckOffDate.present) {
      final v = skillsCheckOffDate.value;
      if (!nullToAbsent || v != null) map['skills_check_off_date'] = Variable<DateTime>(v!);
    }
    if (issueDate.present) {
      final v = issueDate.value;
      if (!nullToAbsent || v != null) map['issue_date'] = Variable<DateTime>(v!);
    }
    if (createdAt.present) map['created_at'] = Variable<DateTime>(createdAt.value);
    if (updatedAt.present) map['updated_at'] = Variable<DateTime>(updatedAt.value);
    return map;
  }
}

class $ChecklistAttemptsTable extends ChecklistAttempts with TableInfo<$ChecklistAttemptsTable, ChecklistAttempt> {
  @override
  final GeneratedDatabase attachedDatabase;
  final String? _alias;
  $ChecklistAttemptsTable(this.attachedDatabase, [this._alias]);

  @override
  late final GeneratedColumn<String> id = GeneratedColumn<String>('id', aliasedName, false, type: DriftSqlType.string, requiredDuringInsert: true);
  @override
  late final GeneratedColumn<String> classId = GeneratedColumn<String>(
    'class_id',
    aliasedName,
    false,
    type: DriftSqlType.string,
    requiredDuringInsert: true,
    defaultConstraints: GeneratedColumn.constraintIsAlways('REFERENCES "class_records" ("id") ON DELETE RESTRICT'),
  );
  @override
  late final GeneratedColumn<String> studentId = GeneratedColumn<String>(
    'student_id',
    aliasedName,
    false,
    type: DriftSqlType.string,
    requiredDuringInsert: true,
    defaultConstraints: GeneratedColumn.constraintIsAlways('REFERENCES "student_records" ("id") ON DELETE RESTRICT'),
  );
  @override
  late final GeneratedColumnWithTypeConverter<ChecklistType, String> checklistType = GeneratedColumn<String>(
    'checklist_type',
    aliasedName,
    false,
    type: DriftSqlType.string,
    requiredDuringInsert: true,
  ).withConverter<ChecklistType>(const ChecklistTypeConverter());
  @override
  late final GeneratedColumnWithTypeConverter<ChecklistAttemptStatus, String> status = GeneratedColumn<String>(
    'status',
    aliasedName,
    false,
    type: DriftSqlType.string,
    requiredDuringInsert: true,
  ).withConverter<ChecklistAttemptStatus>(const ChecklistAttemptStatusConverter());
  @override
  late final GeneratedColumn<bool> finalized = GeneratedColumn<bool>(
    'finalized',
    aliasedName,
    false,
    type: DriftSqlType.bool,
    requiredDuringInsert: false,
    defaultConstraints: GeneratedColumn.constraintIsAlways('CHECK ("finalized" IN (0, 1))'),
    defaultValue: const Constant(false),
  );
  @override
  late final GeneratedColumn<DateTime> finalizedAt = GeneratedColumn<DateTime>('finalized_at', aliasedName, true, type: DriftSqlType.dateTime, requiredDuringInsert: false);
  @override
  late final GeneratedColumn<DateTime> createdAt = GeneratedColumn<DateTime>('created_at', aliasedName, false, type: DriftSqlType.dateTime, requiredDuringInsert: true);
  @override
  late final GeneratedColumn<DateTime> updatedAt = GeneratedColumn<DateTime>('updated_at', aliasedName, false, type: DriftSqlType.dateTime, requiredDuringInsert: true);

  @override
  List<GeneratedColumn> get $columns => [id, classId, studentId, checklistType, status, finalized, finalizedAt, createdAt, updatedAt];

  @override
  String get aliasedName => _alias ?? 'checklist_attempts';
  @override
  String get actualTableName => 'checklist_attempts';

  @override
  VerificationContext validateIntegrity(Insertable<ChecklistAttempt> instance, {bool isInserting = false}) {
    final ctx = VerificationContext();
    final data = instance.toColumns(true);
    if (data.containsKey('id')) ctx.handle(const VerificationMeta('id'), id.isAcceptableOrUnknown(data['id']!, const VerificationMeta('id')));
    if (data.containsKey('class_id')) ctx.handle(const VerificationMeta('classId'), classId.isAcceptableOrUnknown(data['class_id']!, const VerificationMeta('classId')));
    if (data.containsKey('student_id')) ctx.handle(const VerificationMeta('studentId'), studentId.isAcceptableOrUnknown(data['student_id']!, const VerificationMeta('studentId')));
    if (data.containsKey('finalized')) ctx.handle(const VerificationMeta('finalized'), finalized.isAcceptableOrUnknown(data['finalized']!, const VerificationMeta('finalized')));
    if (data.containsKey('finalized_at')) {
      ctx.handle(const VerificationMeta('finalizedAt'), finalizedAt.isAcceptableOrUnknown(data['finalized_at']!, const VerificationMeta('finalizedAt')));
    }
    if (data.containsKey('created_at')) ctx.handle(const VerificationMeta('createdAt'), createdAt.isAcceptableOrUnknown(data['created_at']!, const VerificationMeta('createdAt')));
    if (data.containsKey('updated_at')) ctx.handle(const VerificationMeta('updatedAt'), updatedAt.isAcceptableOrUnknown(data['updated_at']!, const VerificationMeta('updatedAt')));
    return ctx;
  }

  @override
  Set<GeneratedColumn> get $primaryKey => {id};

  @override
  ChecklistAttempt map(Map<String, dynamic> data, {String? tablePrefix}) {
    final effectivePrefix = tablePrefix != null ? '$tablePrefix.' : '';
    return ChecklistAttempt(
      id: attachedDatabase.typeMapping.read(DriftSqlType.string, data['${effectivePrefix}id'])!,
      classId: attachedDatabase.typeMapping.read(DriftSqlType.string, data['${effectivePrefix}class_id'])!,
      studentId: attachedDatabase.typeMapping.read(DriftSqlType.string, data['${effectivePrefix}student_id'])!,
      checklistType: const ChecklistTypeConverter().fromSql(attachedDatabase.typeMapping.read(DriftSqlType.string, data['${effectivePrefix}checklist_type'])!),
      status: const ChecklistAttemptStatusConverter().fromSql(attachedDatabase.typeMapping.read(DriftSqlType.string, data['${effectivePrefix}status'])!),
      finalized: attachedDatabase.typeMapping.read(DriftSqlType.bool, data['${effectivePrefix}finalized'])!,
      finalizedAt: attachedDatabase.typeMapping.read(DriftSqlType.dateTime, data['${effectivePrefix}finalized_at']),
      createdAt: attachedDatabase.typeMapping.read(DriftSqlType.dateTime, data['${effectivePrefix}created_at'])!,
      updatedAt: attachedDatabase.typeMapping.read(DriftSqlType.dateTime, data['${effectivePrefix}updated_at'])!,
    );
  }

  @override
  $ChecklistAttemptsTable createAlias(String alias) => $ChecklistAttemptsTable(attachedDatabase, alias);
}

class ChecklistAttempt extends DataClass implements Insertable<ChecklistAttempt> {
  const ChecklistAttempt({
    required this.id,
    required this.classId,
    required this.studentId,
    required this.checklistType,
    required this.status,
    required this.finalized,
    this.finalizedAt,
    required this.createdAt,
    required this.updatedAt,
  });

  final String id;
  final String classId;
  final String studentId;
  final ChecklistType checklistType;
  final ChecklistAttemptStatus status;
  final bool finalized;
  final DateTime? finalizedAt;
  final DateTime createdAt;
  final DateTime updatedAt;

  @override
  Map<String, Expression> toColumns(bool nullToAbsent) {
    final map = <String, Expression>{};
    map['id'] = Variable<String>(id);
    map['class_id'] = Variable<String>(classId);
    map['student_id'] = Variable<String>(studentId);
    map['checklist_type'] = Variable<String>(const ChecklistTypeConverter().toSql(checklistType));
    map['status'] = Variable<String>(const ChecklistAttemptStatusConverter().toSql(status));
    map['finalized'] = Variable<bool>(finalized);
    if (!nullToAbsent || finalizedAt != null) map['finalized_at'] = Variable<DateTime>(finalizedAt!);
    map['created_at'] = Variable<DateTime>(createdAt);
    map['updated_at'] = Variable<DateTime>(updatedAt);
    return map;
  }

  ChecklistAttemptsCompanion toCompanion(bool nullToAbsent) => ChecklistAttemptsCompanion(
    id: Value(id),
    classId: Value(classId),
    studentId: Value(studentId),
    checklistType: Value(checklistType),
    status: Value(status),
    finalized: Value(finalized),
    finalizedAt: finalizedAt == null && nullToAbsent ? const Value.absent() : Value(finalizedAt),
    createdAt: Value(createdAt),
    updatedAt: Value(updatedAt),
  );

  @override
  Map<String, dynamic> toJson({ValueSerializer? serializer}) {
    serializer ??= driftRuntimeOptions.defaultSerializer;
    return <String, dynamic>{
      'id': serializer.toJson<String>(id),
      'classId': serializer.toJson<String>(classId),
      'studentId': serializer.toJson<String>(studentId),
      'checklistType': serializer.toJson<String>(const ChecklistTypeConverter().toSql(checklistType)),
      'status': serializer.toJson<String>(const ChecklistAttemptStatusConverter().toSql(status)),
      'finalized': serializer.toJson<bool>(finalized),
      'finalizedAt': serializer.toJson<DateTime?>(finalizedAt),
      'createdAt': serializer.toJson<DateTime>(createdAt),
      'updatedAt': serializer.toJson<DateTime>(updatedAt),
    };
  }
}

class ChecklistAttemptsCompanion extends UpdateCompanion<ChecklistAttempt> {
  const ChecklistAttemptsCompanion({
    this.id = const Value.absent(),
    this.classId = const Value.absent(),
    this.studentId = const Value.absent(),
    this.checklistType = const Value.absent(),
    this.status = const Value.absent(),
    this.finalized = const Value.absent(),
    this.finalizedAt = const Value.absent(),
    this.createdAt = const Value.absent(),
    this.updatedAt = const Value.absent(),
  });

  final Value<String> id;
  final Value<String> classId;
  final Value<String> studentId;
  final Value<ChecklistType> checklistType;
  final Value<ChecklistAttemptStatus> status;
  final Value<bool> finalized;
  final Value<DateTime?> finalizedAt;
  final Value<DateTime> createdAt;
  final Value<DateTime> updatedAt;

  @override
  Map<String, Expression> toColumns(bool nullToAbsent) {
    final map = <String, Expression>{};
    if (id.present) map['id'] = Variable<String>(id.value);
    if (classId.present) map['class_id'] = Variable<String>(classId.value);
    if (studentId.present) map['student_id'] = Variable<String>(studentId.value);
    if (checklistType.present) map['checklist_type'] = Variable<String>(const ChecklistTypeConverter().toSql(checklistType.value));
    if (status.present) map['status'] = Variable<String>(const ChecklistAttemptStatusConverter().toSql(status.value));
    if (finalized.present) map['finalized'] = Variable<bool>(finalized.value);
    if (finalizedAt.present) {
      final v = finalizedAt.value;
      if (!nullToAbsent || v != null) map['finalized_at'] = Variable<DateTime>(v!);
    }
    if (createdAt.present) map['created_at'] = Variable<DateTime>(createdAt.value);
    if (updatedAt.present) map['updated_at'] = Variable<DateTime>(updatedAt.value);
    return map;
  }
}

class $ChecklistItemResultsTable extends ChecklistItemResults with TableInfo<$ChecklistItemResultsTable, ChecklistItemResult> {
  @override
  final GeneratedDatabase attachedDatabase;
  final String? _alias;
  $ChecklistItemResultsTable(this.attachedDatabase, [this._alias]);

  @override
  late final GeneratedColumn<String> id = GeneratedColumn<String>('id', aliasedName, false, type: DriftSqlType.string, requiredDuringInsert: true);
  @override
  late final GeneratedColumn<String> attemptId = GeneratedColumn<String>(
    'attempt_id',
    aliasedName,
    false,
    type: DriftSqlType.string,
    requiredDuringInsert: true,
    defaultConstraints: GeneratedColumn.constraintIsAlways('REFERENCES "checklist_attempts" ("id") ON DELETE RESTRICT'),
  );
  @override
  late final GeneratedColumn<String> itemId = GeneratedColumn<String>('item_id', aliasedName, false, type: DriftSqlType.string, requiredDuringInsert: true);
  @override
  late final GeneratedColumnWithTypeConverter<ChecklistItemResultValue, String> result = GeneratedColumn<String>(
    'result',
    aliasedName,
    false,
    type: DriftSqlType.string,
    requiredDuringInsert: true,
  ).withConverter<ChecklistItemResultValue>(const ChecklistItemResultValueConverter());
  @override
  late final GeneratedColumn<String> notes = GeneratedColumn<String>('notes', aliasedName, true, type: DriftSqlType.string, requiredDuringInsert: false);
  @override
  late final GeneratedColumn<DateTime> createdAt = GeneratedColumn<DateTime>('created_at', aliasedName, false, type: DriftSqlType.dateTime, requiredDuringInsert: true);
  @override
  late final GeneratedColumn<DateTime> updatedAt = GeneratedColumn<DateTime>('updated_at', aliasedName, false, type: DriftSqlType.dateTime, requiredDuringInsert: true);

  @override
  List<GeneratedColumn> get $columns => [id, attemptId, itemId, result, notes, createdAt, updatedAt];
  @override
  String get aliasedName => _alias ?? 'checklist_item_results';
  @override
  String get actualTableName => 'checklist_item_results';

  @override
  VerificationContext validateIntegrity(Insertable<ChecklistItemResult> instance, {bool isInserting = false}) {
    final ctx = VerificationContext();
    final data = instance.toColumns(true);
    if (data.containsKey('id')) ctx.handle(const VerificationMeta('id'), id.isAcceptableOrUnknown(data['id']!, const VerificationMeta('id')));
    if (data.containsKey('attempt_id')) {
      ctx.handle(const VerificationMeta('attemptId'), attemptId.isAcceptableOrUnknown(data['attempt_id']!, const VerificationMeta('attemptId')));
    }
    if (data.containsKey('item_id')) ctx.handle(const VerificationMeta('itemId'), itemId.isAcceptableOrUnknown(data['item_id']!, const VerificationMeta('itemId')));
    if (data.containsKey('notes')) ctx.handle(const VerificationMeta('notes'), notes.isAcceptableOrUnknown(data['notes']!, const VerificationMeta('notes')));
    if (data.containsKey('created_at')) ctx.handle(const VerificationMeta('createdAt'), createdAt.isAcceptableOrUnknown(data['created_at']!, const VerificationMeta('createdAt')));
    if (data.containsKey('updated_at')) ctx.handle(const VerificationMeta('updatedAt'), updatedAt.isAcceptableOrUnknown(data['updated_at']!, const VerificationMeta('updatedAt')));
    return ctx;
  }
  @override
  Set<GeneratedColumn> get $primaryKey => {id};

  @override
  ChecklistItemResult map(Map<String, dynamic> data, {String? tablePrefix}) {
    final effectivePrefix = tablePrefix != null ? '$tablePrefix.' : '';
    return ChecklistItemResult(
      id: attachedDatabase.typeMapping.read(DriftSqlType.string, data['${effectivePrefix}id'])!,
      attemptId: attachedDatabase.typeMapping.read(DriftSqlType.string, data['${effectivePrefix}attempt_id'])!,
      itemId: attachedDatabase.typeMapping.read(DriftSqlType.string, data['${effectivePrefix}item_id'])!,
      result: const ChecklistItemResultValueConverter().fromSql(attachedDatabase.typeMapping.read(DriftSqlType.string, data['${effectivePrefix}result'])!),
      notes: attachedDatabase.typeMapping.read(DriftSqlType.string, data['${effectivePrefix}notes']),
      createdAt: attachedDatabase.typeMapping.read(DriftSqlType.dateTime, data['${effectivePrefix}created_at'])!,
      updatedAt: attachedDatabase.typeMapping.read(DriftSqlType.dateTime, data['${effectivePrefix}updated_at'])!,
    );
  }

  @override
  $ChecklistItemResultsTable createAlias(String alias) => $ChecklistItemResultsTable(attachedDatabase, alias);
}

class ChecklistItemResult extends DataClass implements Insertable<ChecklistItemResult> {
  const ChecklistItemResult({
    required this.id,
    required this.attemptId,
    required this.itemId,
    required this.result,
    this.notes,
    required this.createdAt,
    required this.updatedAt,
  });

  final String id;
  final String attemptId;
  final String itemId;
  final ChecklistItemResultValue result;
  final String? notes;
  final DateTime createdAt;
  final DateTime updatedAt;

  @override
  Map<String, Expression> toColumns(bool nullToAbsent) {
    final map = <String, Expression>{};
    map['id'] = Variable<String>(id);
    map['attempt_id'] = Variable<String>(attemptId);
    map['item_id'] = Variable<String>(itemId);
    map['result'] = Variable<String>(const ChecklistItemResultValueConverter().toSql(result));
    if (!nullToAbsent || notes != null) map['notes'] = Variable<String>(notes!);
    map['created_at'] = Variable<DateTime>(createdAt);
    map['updated_at'] = Variable<DateTime>(updatedAt);
    return map;
  }

  ChecklistItemResultsCompanion toCompanion(bool nullToAbsent) => ChecklistItemResultsCompanion(
    id: Value(id),
    attemptId: Value(attemptId),
    itemId: Value(itemId),
    result: Value(result),
    notes: notes == null && nullToAbsent ? const Value.absent() : Value(notes),
    createdAt: Value(createdAt),
    updatedAt: Value(updatedAt),
  );

  @override
  Map<String, dynamic> toJson({ValueSerializer? serializer}) {
    serializer ??= driftRuntimeOptions.defaultSerializer;
    return <String, dynamic>{
      'id': serializer.toJson<String>(id),
      'attemptId': serializer.toJson<String>(attemptId),
      'itemId': serializer.toJson<String>(itemId),
      'result': serializer.toJson<String>(const ChecklistItemResultValueConverter().toSql(result)),
      'notes': serializer.toJson<String?>(notes),
      'createdAt': serializer.toJson<DateTime>(createdAt),
      'updatedAt': serializer.toJson<DateTime>(updatedAt),
    };
  }
}

class ChecklistItemResultsCompanion extends UpdateCompanion<ChecklistItemResult> {
  const ChecklistItemResultsCompanion({
    this.id = const Value.absent(),
    this.attemptId = const Value.absent(),
    this.itemId = const Value.absent(),
    this.result = const Value.absent(),
    this.notes = const Value.absent(),
    this.createdAt = const Value.absent(),
    this.updatedAt = const Value.absent(),
  });

  final Value<String> id;
  final Value<String> attemptId;
  final Value<String> itemId;
  final Value<ChecklistItemResultValue> result;
  final Value<String?> notes;
  final Value<DateTime> createdAt;
  final Value<DateTime> updatedAt;

  @override
  Map<String, Expression> toColumns(bool nullToAbsent) {
    final map = <String, Expression>{};
    if (id.present) map['id'] = Variable<String>(id.value);
    if (attemptId.present) map['attempt_id'] = Variable<String>(attemptId.value);
    if (itemId.present) map['item_id'] = Variable<String>(itemId.value);
    if (result.present) map['result'] = Variable<String>(const ChecklistItemResultValueConverter().toSql(result.value));
    if (notes.present) {
      final v = notes.value;
      if (!nullToAbsent || v != null) map['notes'] = Variable<String>(v!);
    }
    if (createdAt.present) map['created_at'] = Variable<DateTime>(createdAt.value);
    if (updatedAt.present) map['updated_at'] = Variable<DateTime>(updatedAt.value);
    return map;
  }
}

class $CcfSessionsTable extends CcfSessions with TableInfo<$CcfSessionsTable, CcfSession> {
  @override
  final GeneratedDatabase attachedDatabase;
  final String? _alias;
  $CcfSessionsTable(this.attachedDatabase, [this._alias]);

  @override
  late final GeneratedColumn<String> id = GeneratedColumn<String>('id', aliasedName, false, type: DriftSqlType.string, requiredDuringInsert: true);
  @override
  late final GeneratedColumn<String> classId = GeneratedColumn<String>(
    'class_id',
    aliasedName,
    true,
    type: DriftSqlType.string,
    requiredDuringInsert: false,
    defaultConstraints: GeneratedColumn.constraintIsAlways('REFERENCES "class_records" ("id") ON DELETE SET NULL'),
  );
  @override
  late final GeneratedColumn<String> studentId = GeneratedColumn<String>(
    'student_id',
    aliasedName,
    true,
    type: DriftSqlType.string,
    requiredDuringInsert: false,
    defaultConstraints: GeneratedColumn.constraintIsAlways('REFERENCES "student_records" ("id") ON DELETE SET NULL'),
  );
  @override
  late final GeneratedColumn<DateTime> startedAt = GeneratedColumn<DateTime>('started_at', aliasedName, false, type: DriftSqlType.dateTime, requiredDuringInsert: true);
  @override
  late final GeneratedColumn<DateTime> endedAt = GeneratedColumn<DateTime>('ended_at', aliasedName, true, type: DriftSqlType.dateTime, requiredDuringInsert: false);
  @override
  late final GeneratedColumn<int> totalDurationMilliseconds = GeneratedColumn<int>('total_duration_milliseconds', aliasedName, false, type: DriftSqlType.int, requiredDuringInsert: true);
  @override
  late final GeneratedColumn<int> compressionDurationMilliseconds = GeneratedColumn<int>('compression_duration_milliseconds', aliasedName, false, type: DriftSqlType.int, requiredDuringInsert: true);
  @override
  late final GeneratedColumn<int> pauseDurationMilliseconds = GeneratedColumn<int>('pause_duration_milliseconds', aliasedName, false, type: DriftSqlType.int, requiredDuringInsert: true);
  @override
  late final GeneratedColumn<double> ccfPercentage = GeneratedColumn<double>('ccf_percentage', aliasedName, false, type: DriftSqlType.double, requiredDuringInsert: true);
  @override
  late final GeneratedColumn<double> passingThreshold = GeneratedColumn<double>('passing_threshold', aliasedName, false, type: DriftSqlType.double, requiredDuringInsert: true);
  @override
  late final GeneratedColumn<bool> finalized = GeneratedColumn<bool>(
    'finalized',
    aliasedName,
    false,
    type: DriftSqlType.bool,
    requiredDuringInsert: false,
    defaultConstraints: GeneratedColumn.constraintIsAlways('CHECK ("finalized" IN (0, 1))'),
    defaultValue: const Constant(false),
  );
  @override
  late final GeneratedColumnWithTypeConverter<CcfResultValue, String> result = GeneratedColumn<String>(
    'result',
    aliasedName,
    false,
    type: DriftSqlType.string,
    requiredDuringInsert: true,
  ).withConverter<CcfResultValue>(const CcfResultValueConverter());
  @override
  late final GeneratedColumn<DateTime> createdAt = GeneratedColumn<DateTime>('created_at', aliasedName, false, type: DriftSqlType.dateTime, requiredDuringInsert: true);
  @override
  late final GeneratedColumn<DateTime> updatedAt = GeneratedColumn<DateTime>('updated_at', aliasedName, false, type: DriftSqlType.dateTime, requiredDuringInsert: true);

  @override
  List<GeneratedColumn> get $columns => [
    id,
    classId,
    studentId,
    startedAt,
    endedAt,
    totalDurationMilliseconds,
    compressionDurationMilliseconds,
    pauseDurationMilliseconds,
    ccfPercentage,
    passingThreshold,
    finalized,
    result,
    createdAt,
    updatedAt,
  ];
  @override
  String get aliasedName => _alias ?? 'ccf_sessions';
  @override
  String get actualTableName => 'ccf_sessions';

  @override
  VerificationContext validateIntegrity(Insertable<CcfSession> instance, {bool isInserting = false}) {
    final ctx = VerificationContext();
    final data = instance.toColumns(true);
    if (data.containsKey('id')) ctx.handle(const VerificationMeta('id'), id.isAcceptableOrUnknown(data['id']!, const VerificationMeta('id')));
    if (data.containsKey('class_id')) ctx.handle(const VerificationMeta('classId'), classId.isAcceptableOrUnknown(data['class_id']!, const VerificationMeta('classId')));
    if (data.containsKey('student_id')) ctx.handle(const VerificationMeta('studentId'), studentId.isAcceptableOrUnknown(data['student_id']!, const VerificationMeta('studentId')));
    if (data.containsKey('started_at')) ctx.handle(const VerificationMeta('startedAt'), startedAt.isAcceptableOrUnknown(data['started_at']!, const VerificationMeta('startedAt')));
    if (data.containsKey('ended_at')) ctx.handle(const VerificationMeta('endedAt'), endedAt.isAcceptableOrUnknown(data['ended_at']!, const VerificationMeta('endedAt')));
    if (data.containsKey('total_duration_milliseconds')) {
      ctx.handle(
        const VerificationMeta('totalDurationMilliseconds'),
        totalDurationMilliseconds.isAcceptableOrUnknown(data['total_duration_milliseconds']!, const VerificationMeta('totalDurationMilliseconds')),
      );
    }
    if (data.containsKey('compression_duration_milliseconds')) {
      ctx.handle(
        const VerificationMeta('compressionDurationMilliseconds'),
        compressionDurationMilliseconds.isAcceptableOrUnknown(
          data['compression_duration_milliseconds']!,
          const VerificationMeta('compressionDurationMilliseconds'),
        ),
      );
    }
    if (data.containsKey('pause_duration_milliseconds')) {
      ctx.handle(
        const VerificationMeta('pauseDurationMilliseconds'),
        pauseDurationMilliseconds.isAcceptableOrUnknown(data['pause_duration_milliseconds']!, const VerificationMeta('pauseDurationMilliseconds')),
      );
    }
    if (data.containsKey('ccf_percentage')) ctx.handle(const VerificationMeta('ccfPercentage'), ccfPercentage.isAcceptableOrUnknown(data['ccf_percentage']!, const VerificationMeta('ccfPercentage')));
    if (data.containsKey('passing_threshold')) {
      ctx.handle(const VerificationMeta('passingThreshold'), passingThreshold.isAcceptableOrUnknown(data['passing_threshold']!, const VerificationMeta('passingThreshold')));
    }
    if (data.containsKey('finalized')) ctx.handle(const VerificationMeta('finalized'), finalized.isAcceptableOrUnknown(data['finalized']!, const VerificationMeta('finalized')));
    if (data.containsKey('created_at')) ctx.handle(const VerificationMeta('createdAt'), createdAt.isAcceptableOrUnknown(data['created_at']!, const VerificationMeta('createdAt')));
    if (data.containsKey('updated_at')) ctx.handle(const VerificationMeta('updatedAt'), updatedAt.isAcceptableOrUnknown(data['updated_at']!, const VerificationMeta('updatedAt')));
    return ctx;
  }
  @override
  Set<GeneratedColumn> get $primaryKey => {id};

  @override
  CcfSession map(Map<String, dynamic> data, {String? tablePrefix}) {
    final effectivePrefix = tablePrefix != null ? '$tablePrefix.' : '';
    return CcfSession(
      id: attachedDatabase.typeMapping.read(DriftSqlType.string, data['${effectivePrefix}id'])!,
      classId: attachedDatabase.typeMapping.read(DriftSqlType.string, data['${effectivePrefix}class_id']),
      studentId: attachedDatabase.typeMapping.read(DriftSqlType.string, data['${effectivePrefix}student_id']),
      startedAt: attachedDatabase.typeMapping.read(DriftSqlType.dateTime, data['${effectivePrefix}started_at'])!,
      endedAt: attachedDatabase.typeMapping.read(DriftSqlType.dateTime, data['${effectivePrefix}ended_at']),
      totalDurationMilliseconds: attachedDatabase.typeMapping.read(DriftSqlType.int, data['${effectivePrefix}total_duration_milliseconds'])!,
      compressionDurationMilliseconds: attachedDatabase.typeMapping.read(DriftSqlType.int, data['${effectivePrefix}compression_duration_milliseconds'])!,
      pauseDurationMilliseconds: attachedDatabase.typeMapping.read(DriftSqlType.int, data['${effectivePrefix}pause_duration_milliseconds'])!,
      ccfPercentage: attachedDatabase.typeMapping.read(DriftSqlType.double, data['${effectivePrefix}ccf_percentage'])!,
      passingThreshold: attachedDatabase.typeMapping.read(DriftSqlType.double, data['${effectivePrefix}passing_threshold'])!,
      finalized: attachedDatabase.typeMapping.read(DriftSqlType.bool, data['${effectivePrefix}finalized'])!,
      result: const CcfResultValueConverter().fromSql(attachedDatabase.typeMapping.read(DriftSqlType.string, data['${effectivePrefix}result'])!),
      createdAt: attachedDatabase.typeMapping.read(DriftSqlType.dateTime, data['${effectivePrefix}created_at'])!,
      updatedAt: attachedDatabase.typeMapping.read(DriftSqlType.dateTime, data['${effectivePrefix}updated_at'])!,
    );
  }

  @override
  $CcfSessionsTable createAlias(String alias) => $CcfSessionsTable(attachedDatabase, alias);
}

class CcfSession extends DataClass implements Insertable<CcfSession> {
  const CcfSession({
    required this.id,
    this.classId,
    this.studentId,
    required this.startedAt,
    this.endedAt,
    required this.totalDurationMilliseconds,
    required this.compressionDurationMilliseconds,
    required this.pauseDurationMilliseconds,
    required this.ccfPercentage,
    required this.passingThreshold,
    required this.finalized,
    required this.result,
    required this.createdAt,
    required this.updatedAt,
  });

  final String id;
  final String? classId;
  final String? studentId;
  final DateTime startedAt;
  final DateTime? endedAt;
  final int totalDurationMilliseconds;
  final int compressionDurationMilliseconds;
  final int pauseDurationMilliseconds;
  final double ccfPercentage;
  final double passingThreshold;
  final bool finalized;
  final CcfResultValue result;
  final DateTime createdAt;
  final DateTime updatedAt;

  @override
  Map<String, Expression> toColumns(bool nullToAbsent) {
    final map = <String, Expression>{};
    map['id'] = Variable<String>(id);
    if (!nullToAbsent || classId != null) map['class_id'] = Variable<String>(classId!);
    if (!nullToAbsent || studentId != null) map['student_id'] = Variable<String>(studentId!);
    map['started_at'] = Variable<DateTime>(startedAt);
    if (!nullToAbsent || endedAt != null) map['ended_at'] = Variable<DateTime>(endedAt!);
    map['total_duration_milliseconds'] = Variable<int>(totalDurationMilliseconds);
    map['compression_duration_milliseconds'] = Variable<int>(compressionDurationMilliseconds);
    map['pause_duration_milliseconds'] = Variable<int>(pauseDurationMilliseconds);
    map['ccf_percentage'] = Variable<double>(ccfPercentage);
    map['passing_threshold'] = Variable<double>(passingThreshold);
    map['finalized'] = Variable<bool>(finalized);
    map['result'] = Variable<String>(const CcfResultValueConverter().toSql(result));
    map['created_at'] = Variable<DateTime>(createdAt);
    map['updated_at'] = Variable<DateTime>(updatedAt);
    return map;
  }

  CcfSessionsCompanion toCompanion(bool nullToAbsent) => CcfSessionsCompanion(
    id: Value(id),
    classId: classId == null && nullToAbsent ? const Value.absent() : Value(classId),
    studentId: studentId == null && nullToAbsent ? const Value.absent() : Value(studentId),
    startedAt: Value(startedAt),
    endedAt: endedAt == null && nullToAbsent ? const Value.absent() : Value(endedAt),
    totalDurationMilliseconds: Value(totalDurationMilliseconds),
    compressionDurationMilliseconds: Value(compressionDurationMilliseconds),
    pauseDurationMilliseconds: Value(pauseDurationMilliseconds),
    ccfPercentage: Value(ccfPercentage),
    passingThreshold: Value(passingThreshold),
    finalized: Value(finalized),
    result: Value(result),
    createdAt: Value(createdAt),
    updatedAt: Value(updatedAt),
  );

  @override
  Map<String, dynamic> toJson({ValueSerializer? serializer}) {
    serializer ??= driftRuntimeOptions.defaultSerializer;
    return <String, dynamic>{
      'id': serializer.toJson<String>(id),
      'classId': serializer.toJson<String?>(classId),
      'studentId': serializer.toJson<String?>(studentId),
      'startedAt': serializer.toJson<DateTime>(startedAt),
      'endedAt': serializer.toJson<DateTime?>(endedAt),
      'totalDurationMilliseconds': serializer.toJson<int>(totalDurationMilliseconds),
      'compressionDurationMilliseconds': serializer.toJson<int>(compressionDurationMilliseconds),
      'pauseDurationMilliseconds': serializer.toJson<int>(pauseDurationMilliseconds),
      'ccfPercentage': serializer.toJson<double>(ccfPercentage),
      'passingThreshold': serializer.toJson<double>(passingThreshold),
      'finalized': serializer.toJson<bool>(finalized),
      'result': serializer.toJson<String>(const CcfResultValueConverter().toSql(result)),
      'createdAt': serializer.toJson<DateTime>(createdAt),
      'updatedAt': serializer.toJson<DateTime>(updatedAt),
    };
  }
}

class CcfSessionsCompanion extends UpdateCompanion<CcfSession> {
  const CcfSessionsCompanion({
    this.id = const Value.absent(),
    this.classId = const Value.absent(),
    this.studentId = const Value.absent(),
    this.startedAt = const Value.absent(),
    this.endedAt = const Value.absent(),
    this.totalDurationMilliseconds = const Value.absent(),
    this.compressionDurationMilliseconds = const Value.absent(),
    this.pauseDurationMilliseconds = const Value.absent(),
    this.ccfPercentage = const Value.absent(),
    this.passingThreshold = const Value.absent(),
    this.finalized = const Value.absent(),
    this.result = const Value.absent(),
    this.createdAt = const Value.absent(),
    this.updatedAt = const Value.absent(),
  });

  final Value<String> id;
  final Value<String?> classId;
  final Value<String?> studentId;
  final Value<DateTime> startedAt;
  final Value<DateTime?> endedAt;
  final Value<int> totalDurationMilliseconds;
  final Value<int> compressionDurationMilliseconds;
  final Value<int> pauseDurationMilliseconds;
  final Value<double> ccfPercentage;
  final Value<double> passingThreshold;
  final Value<bool> finalized;
  final Value<CcfResultValue> result;
  final Value<DateTime> createdAt;
  final Value<DateTime> updatedAt;

  @override
  Map<String, Expression> toColumns(bool nullToAbsent) {
    final map = <String, Expression>{};
    if (id.present) map['id'] = Variable<String>(id.value);
    if (classId.present) {
      final v = classId.value;
      if (!nullToAbsent || v != null) map['class_id'] = Variable<String>(v!);
    }
    if (studentId.present) {
      final v = studentId.value;
      if (!nullToAbsent || v != null) map['student_id'] = Variable<String>(v!);
    }
    if (startedAt.present) map['started_at'] = Variable<DateTime>(startedAt.value);
    if (endedAt.present) {
      final v = endedAt.value;
      if (!nullToAbsent || v != null) map['ended_at'] = Variable<DateTime>(v!);
    }
    if (totalDurationMilliseconds.present) map['total_duration_milliseconds'] = Variable<int>(totalDurationMilliseconds.value);
    if (compressionDurationMilliseconds.present) {
      map['compression_duration_milliseconds'] = Variable<int>(compressionDurationMilliseconds.value);
    }
    if (pauseDurationMilliseconds.present) map['pause_duration_milliseconds'] = Variable<int>(pauseDurationMilliseconds.value);
    if (ccfPercentage.present) map['ccf_percentage'] = Variable<double>(ccfPercentage.value);
    if (passingThreshold.present) map['passing_threshold'] = Variable<double>(passingThreshold.value);
    if (finalized.present) map['finalized'] = Variable<bool>(finalized.value);
    if (result.present) map['result'] = Variable<String>(const CcfResultValueConverter().toSql(result.value));
    if (createdAt.present) map['created_at'] = Variable<DateTime>(createdAt.value);
    if (updatedAt.present) map['updated_at'] = Variable<DateTime>(updatedAt.value);
    return map;
  }
}

abstract class _$AppDatabase extends GeneratedDatabase {
  _$AppDatabase(QueryExecutor e) : super(e);

  late final $ClassRecordsTable classRecords = $ClassRecordsTable(this);
  late final $StudentRecordsTable studentRecords = $StudentRecordsTable(this);
  late final $ChecklistAttemptsTable checklistAttempts = $ChecklistAttemptsTable(this);
  late final $ChecklistItemResultsTable checklistItemResults = $ChecklistItemResultsTable(this);
  late final $CcfSessionsTable ccfSessions = $CcfSessionsTable(this);

  @override
  Iterable<TableInfo<Table, dynamic>> get allTables => [classRecords, studentRecords, checklistAttempts, checklistItemResults, ccfSessions];

  @override
  List<DatabaseSchemaEntity> get allSchemaEntities => [classRecords, studentRecords, checklistAttempts, checklistItemResults, ccfSessions];
}
